### ISSUE TITLE
What's wrong with -t all option for generating projects?

### ISSUE THREAD

**Issue by stalker57241** [oxygine/oxygine-framework#174]
```
Traceback (most recent call last):
  File "D:\programs\oxygine\oxygine-framework\tools\gen_template.py", line 383, in <module>
    run(args)
  File "D:\programs\oxygine\oxygine-framework\tools\gen_template.py", line 67, in run
    _run(args)
  File "D:\programs\oxygine\oxygine-framework\tools\gen_template.py", line 362, in _run
    process_folder(top_path, args.dest + "/")
  File "D:\programs\oxygine\oxygine-framework\tools\gen_template.py", line 303, in process_folder
    for src in os.listdir(path):
               ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'D:\\programs\\oxygine\\oxygine-framework\\tools/templates/proj.all//'
```
When I finally tried to create all templates for projects, this message appeared. Command: `python gen_template.py LearnProject2 --type all -d E:\oxygine\learn_project2` (`-t all` I tried first, but it won't work)

**Comment by stalker57241** [comment]
And what's wrong with generation of projects with python scripts principially?!!!

**Comment by guanka** [comment]
It seems that an error in process_folder(top_path, args.dest + "/"), the windows path separators different from unix system.
