### ISSUE TITLE
Emscripten build problems

### ISSUE THREAD

**Issue by jsaak** [oxygine/oxygine-framework#66]
Could not compile with Emscripten, here are the details:
Any idea what is wrong?

(Same program compiles and runs fine when compiling with gcc to linux)
Also the release build is working as expected.

compile log:

```
[100%] Linking CXX executable HelloWorld.html
WARNING:root:emcc: cannot find library "nul"
warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
warning: unresolved symbol: _ZN7oxygine5ActorD2Ev
warning: unresolved symbol: _ZN7oxygine10RestorableD2Ev
warning: unresolved symbol: _ZN7oxygine8ResourceD2Ev
warning: unresolved symbol: _ZN7oxygine5ActorC2Ev
warning: unresolved symbol: _ZN7oxygine11VStyleActorC2Ev
warning: unresolved symbol: _ZN7oxygine6SpriteD2Ev
warning: unresolved symbol: _ZN7oxygine10ObjectBaseD2Ev
[100%] Built target HelloWorld
```

console error log:

```
HelloWorld.html:1249 pre-main prep time: 136 msModule.printErr @ HelloWorld.html:1249
HelloWorld.html:1237 initialize oxygine
HelloWorld.html:1237 EMSCRIPTEN build
HelloWorld.html:1237 display size: 960 640
HelloWorld.html:1237 ZipFS, total files: 13
HelloWorld.html:1237 oxygine initialized
HelloWorld.html:1237 ZipFS, total files: 13
HelloWorld.html:1249 missing function: _ZN7oxygine6SpriteD2EvModule.printErr @ HelloWorld.html:1249
HelloWorld.html:1237 -1
HelloWorld.html:1249 -1Module.printErr @ HelloWorld.html:1249
HelloWorld.html:1249 warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demanglingModule.printErr @ HelloWorld.html:1249
HelloWorld.js:313372 Uncaught abort(-1) at Error
    at jsStackTrace (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:1134:13)
    at stackTrace (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:1151:22)
    at abort (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:313477:44)
    at __ZN7oxygine6SpriteD2Ev (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:8105:67)
    at __ZN7oxygine12MaskedSpriteD2Ev (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:187623:2)
    at Array.__ZN7oxygine12MaskedSpriteD0Ev (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:187633:2)
    at __ZN7oxygine11ref_counter10releaseRefEv (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:14819:30)
    at Array.__ZN7oxygine21intrusive_ptr_releaseEPNS_11ref_counterE (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:14796:2)
    at Object.dynCall_vi (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:310134:32)
    at invoke_vi (file:///home/jsaak/svn/jsaak/dyna/proj.cmake/build_emsc/HelloWorld.js:9061:25)
```

emsdk:

```
$ ./emsdk list     

The following precompiled tool packages are available for download:
           node-4.1.1-32bit         
    (*)    node-4.1.1-64bit         	INSTALLED
           emscripten-1.30.0        
           emscripten-1.34.1        
           emscripten-1.35.0        

The following tools can be compiled from source:
           clang-tag-e1.36.4-32bit  
           clang-tag-e1.36.5-32bit  
           clang-tag-e1.36.4-64bit  
           clang-tag-e1.36.5-64bit  
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
    (*)    clang-master-64bit       	INSTALLED
           emscripten-tag-1.36.4-32bit
           emscripten-tag-1.36.5-32bit
           emscripten-tag-1.36.4-64bit
           emscripten-tag-1.36.5-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
    (*)    emscripten-master-64bit  	INSTALLED

The following precompiled SDKs are available for download:

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit       
         sdk-master-32bit         
    *    sdk-master-64bit         	INSTALLED
         sdk-tag-1.36.4-32bit     
         sdk-tag-1.36.5-32bit     

Items marked with * are activated for the current user.
Items marked with (*) are selected for use, but your current shell environment is not configured to use them. Type "source ./emsdk_env.sh" to set up your current shell to use them.

To access the historical archived versions, type 'emsdk list --old'
```

**Comment by frankinshtein** [comment]
you are using not stable version of emscripten
latest released emscripten is 1.35.0
